language: php

branches:
  only:
  - master

matrix:
  include:
  - name: "MySQL 5.5 on Precise"
    dist: precise
    services:
    - mysql
  - name: "MySQL 5.6 on Trusty"
    dist: trusty
    services:
    - mysql
  - name: "MySQL 5.7 on Xenial"
    dist: xenial
    services:
    - mysql
    env: SET_SQL_MODE=y
  - name: "MariaDB 10.0 on Trusty"
    dist: trusty
    addons:
      mariadb: '10.0'
  - name: "MariaDB 10.4 on Xenial"
    dist: xenial
    addons:
      mariadb: '10.4'

before_script:
  - mysqladmin -h 127.0.0.1 -u root create trackserver
  - export SET_SQL_MODE

script: ./test.sh
